### ISSUE TITLE
Requested changes to tabs, homepage, diets, production, and about (2016_2_16)

### ISSUE THREAD

**Issue by ColinKhoury** [CIAT-DAPA/cwr_interdependence#1]
Tabs:
• Change “Interdependence” tab to “Home”
• highlight the tab that is currently selected (in different color)
• make the tab letters bigger/bold or somehow more visible
• Move tabs to the middle of page? (justified)

Home page:
• Increase size of “Where our food crops come from”
• Increase size (slightly) of “Explore…”
• Delete “Learn more” box
• Map- in circle, photo of map
• Change “View details” to “View”/ OR delete “View details” and make the link directly from image
• Diets- in circle, photo of diets circus (calories is good)
• Production- in circle, photo of production circus (prod quantity is good)
• Homepage text changed in gdoc. Please replace

Diets:
• Text update (Harold to do in code from gdoc and give code to stevie)
o   “explore text” – need to update- done
o   West Africa – Cote- done
o   West Asia – Sesame;- done
o   S Asia – Sugarcane ( - done
o   Trop s America – mate (tea commodity) – done
o   Make “hover” bold - done
• Flows- better to have 1 decimal in values, not two
• Change “Source” to “Origin” and “Target” to “Consumer” (OR figure out the flecha or other option!
• Make “Total: xxx” a bit smaller font 
• Hover box at regions on right gets cutoff? (e.g. C Africa)
• Cottonseed oil icon seems to be cutoff at left?
• Some regions seem to have weird letters still on the circos (e.g. Temp S America)
• Consider moving bottom text to an expandable tab or something (called “About the plot”)
• I think we need to find a way to make more visible in right side data that the values are calories/capita/day, etc.  How to do this?
• Explore making a map instead of listing of countries

Production:
• Text update (Harold to do in code from gdoc and give code to stevie)
o   “explore text” – need to update- done
o   West Africa – Cote- done
o   Make “hover” bold - done
• Change “Source” to “Origin” and “Target” to “Consumer” (OR figure out the flecha or other option!
• Make “Total: xxx” a bit smaller font 
• Hover box at regions on right gets cutoff? (e.g. C Africa)
• Cottonseed oil icon seems to be cutoff at left?
• ***Fix top 5 crops error (Harold working on this)
• Some regions seem to have weird letters still on the circos (e.g. Temp S America)
• Consider moving bottom text to an expandable tab or something (called “About the plot”)
• I think we need to find a way to make more visible in right side data that the values are tonnes, ha, $US million, etc.  How to do this?
• Explore making a map instead of listing of countries

About:
• Hice revisions al gdoc https://docs.google.com/document/d/1OkSCgM3NNCJhjBlrjQ6jfm3R4M-8nYuSfNKW53z8zC4/edit. Favor update.
• Insert ccby icon (image)
• Should we provide link to Global flow github only (currently) or to our own github?
• Links on “remained in food supplies data, and 132 crop commodities in production data.” Should be deleted. Nada de enlace alli, porfa.
• Insert link to crops regions table at “See the crops-regions table for a listing of all crops…”  TableS1_crops_regions_table_2015_4_1
• Hay un duplicacion en references (pero no en el gdoc (Vincent et al dos veces)).
• Make “References” title a bit smaller

**Comment by ColinKhoury** [comment]
moved to above

**Comment by ColinKhoury** [comment]
moved to above

**Comment by stevensotelo** [comment]
Split in different issues
