### ISSUE TITLE
circos- confirm that we are showing all flows, not just the most important ones?

### ISSUE THREAD

**Issue by ColinKhoury** [CIAT-DAPA/cwr_interdependence#10]

**Comment by stevensotelo** [comment]
@ColinKhoury 

I set the threshold of the circus in 1 by defect. If any value into the data is lower than 1, it won't show in the circus.

https://github.com/CIAT-DAPA/cwr_interdependence/blob/master/web_app/app/scripts/services/interdependence.js

Line 45

**Comment by ColinKhoury** [comment]
Can you check how different they look w a smaller thresh, like 0.1? Thanks 

Colin Khoury

**Comment by stevensotelo** [comment]
@ColinKhoury 

I changed the parameter in the app

https://github.com/CIAT-DAPA/cwr_interdependence/blob/master/web_app/app/scripts/services/interdependence.js

**Comment by ColinKhoury** [comment]
Confirmed all good.
