### ISSUE TITLE
Circos- FS and Production- region text changes

### ISSUE THREAD

**Issue by ColinKhoury** [CIAT-DAPA/cwr_interdependence#12]
1. change text of regions to list first the crops (in one color or larger text), then list of countries (smaller text and different color). Ojo IOI and ANZ have no native crops.
   note CK already changed text order in google doc

**Comment by haachicanoy** [comment]
1. JSON files updated with text changes and shared to @stevensotelo

**Comment by stevensotelo** [comment]
@ColinKhoury 

I and @haachicanoy has changed the format of the content of the text. We created a styles for every paragraph. Please check it in the web site, because I don't know which color I can use for the text

**Comment by ColinKhoury** [comment]
I think it looks great as it is; but I only see it implemented in Production, not yet in diets?

**Comment by stevensotelo** [comment]
@ColinKhoury 

Fixed
