### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by omarbenites** [CIAT-DAPA/cwr_interdependence#15]
Hello ciat-guys,

I like so much your app about "origin-of-crop" (http://blog.ciat.cgiar.org/origin-of-crops/), looks awesome!
I wonder if you crop icons are free usage or I have to pay something.

Regards.

Ps: Sorry this is not exactly a issue, so you can close it afterwards.

**Comment by cenavarror** [comment]
Hi Omar, 
Some of this icons were free and/or were modified of free vectors. However, we had to buy others many of them. 
Blessings, 
Carlos

**Comment by ColinKhoury** [comment]
Hi Omar, 
Thanks for your note. My memory is that we found about half for free online (and modified some of these to fit what we needed in .ai; the other half we paid for which totaled maybe $60 in total. I think we can find the links to the sites if you need them. Thanks Colin

**Comment by omarbenites** [comment]
It would be great if you share the links. 
Thanks in advance @ColinKhoury  and @cenavarror.
 Omar

**Comment by ColinKhoury** [comment]
Hi Omar, 
Apologies again for not tracking every source or purchase fully. I know that we mostly purchased from iconfinder and gumroad. Attached a spreadsheet with links to the sources of most of what we got. Hope its helpful to you. Colin 
[Items_regions_FSProd_for_map_share.xlsx](https://github.com/CIAT-DAPA/cwr_interdependence/files/311075/Items_regions_FSProd_for_map_share.xlsx)

**Comment by omarbenites** [comment]
Wow, Thank you so much Colin!, it really helps. :+1: 

Omar
