### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/cwr_interdependence#2]
1) Change “Interdependence” tab to “Home”
2) highlight the tab that is currently selected (in different color)
3) make the tab letters bigger/bold or somehow more visible
4) Move tabs to the middle of page? (justified)

**Comment by stevensotelo** [comment]
@ColinKhoury 

1) The common in the web sites is that in this place the website should has its name, for example the name of the domain
2) The current selection shows highlighted
3) I applied bold to the menu items
4) The normal in websites is keep in side the name of the webpage and in the other side the menu of the web site

**Comment by ColinKhoury** [comment]
Hola OK on 1-4, but please change Interdependence to Origins

**Comment by stevensotelo** [comment]
I changed the title
