### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/cwr_interdependence#3]
1) Increase size of “Where our food crops come from”
2) Increase size (slightly) of “Explore…”
 Delete “Learn more” box
3) Map- in circle, photo of map
4) Change “View details” to “View”/ OR delete “View details” and make the link directly from image
5) Diets- in circle, photo of diets circus (calories is good)
6) Production- in circle, photo of production circus (prod quantity is good)
7) Homepage text changed in gdoc. Please replace

**Comment by stevensotelo** [comment]
@ColinKhoury 

1) Fixed
2) Fixed
3) Fixed
4) Fixed
5) Fixed
6) Fixed
7) Fixed

**Comment by ColinKhoury** [comment]
Looks great!
1. please make title even bigger
2. make "explore" center justified

**Comment by stevensotelo** [comment]
@ColinKhoury 

1) Fixed
2) Fixed

**Comment by ColinKhoury** [comment]
Looks brilliant!
