### ISSUE TITLE
Diets

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/cwr_interdependence#4]
1) Text update (Harold to do in code from gdoc and give code to stevie)
o “explore text” – need to update- done
o West Africa – Cote- done
o West Asia – Sesame;- done
o S Asia – Sugarcane ( - done
o Trop s America – mate (tea commodity) – done
o Make “hover” bold - done
2) Flows- better to have 1 decimal in values, not two
3) Change “Source” to “Origin” and “Target” to “Consumer” (OR figure out the flecha or other option!
4) Make “Total: xxx” a bit smaller font 
5) Hover box at regions on right gets cutoff? (e.g. C Africa)
6) Cottonseed oil icon seems to be cutoff at left?
7) Some regions seem to have weird letters still on the circos (e.g. Temp S America)
8) Consider moving bottom text to an expandable tab or something (called “About the plot”)
9) I think we need to find a way to make more visible in right side data that the values are calories/capita/day, etc. How to do this?
10) Explore making a map instead of listing of countries

**Comment by ColinKhoury** [comment]
further revisions:
11. Please bold the name of origin and Consumer regions at right area that appears
12. Total value- I like what you did with putting at bottom, but think its confusing, because Total NOT = to sum of top 5 crops, so people might be confused. I would keep the total above the crops. Is there maybe a way to put "Top 5 crops" or something above the crops?

**Comment by stevensotelo** [comment]
2) Fixed
3) Fixed
4) Fixed
6) The image is cut. We need a new image for this icon
7) The name in the data source is bigger, so it should be smaller, for example: T S Ame
8) We can created a other issue for that. It is a new requirement
9) We need to change the data source. @haachicanoy we should extend the data source to do that
10) we need change the data source and explorer others alternatives. We can created a other issue for that

**Comment by stevensotelo** [comment]
@ColinKhoury 

6) Fixed
9) Fixed

**Comment by ColinKhoury** [comment]
Looking good. 
13. change "Top 5 crops" to "Top crops"

**Comment by stevensotelo** [comment]
@ColinKhoury 

13) Fixed

**Comment by ColinKhoury** [comment]
Excellent
