### ISSUE TITLE
About

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/cwr_interdependence#6]
1) Hice revisions al gdoc https://docs.google.com/document/d/1OkSCgM3NNCJhjBlrjQ6jfm3R4M-8nYuSfNKW53z8zC4/edit. Favor update.
2) Insert ccby icon (image)
3) Should we provide link to Global flow github only (currently) or to our own github?
4) Links on “remained in food supplies data, and 132 crop commodities in production data.” Should be deleted. Nada de enlace alli, porfa.
5) Insert link to crops regions table at “See the crops-regions table for a listing of all crops…” TableS1_crops_regions_table_2015_4_1
6) Hay un duplicacion en references (pero no en el gdoc (Vincent et al dos veces)).
7) Make “References” title a bit smaller

**Comment by ColinKhoury** [comment]
Aqui sobre el icon cc by:
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

https://creativecommons.org/choose/

**Comment by stevensotelo** [comment]
@ColinKhoury 

1) Fixed
2) Fixed
3) Both
4) Fixed
5) Fixed
6) Fixed
7) Fixed

**Comment by ColinKhoury** [comment]
Looking good!

Two things remaining: 
8. for the numbers in the text referring to references, can we place "(" around them
9. lets include a link to our github code for circos when it is ready

**Comment by stevensotelo** [comment]
@ColinKhoury 

1) Fixed
2) Fixed

**Comment by ColinKhoury** [comment]
looks brilliant!

**Comment by stevensotelo** [comment]
@ColinKhoury 

Fixed the content text for the github and numbers inside of paragraph

**Comment by ColinKhoury** [comment]
#9 please move link to work "origins" (not to "source")

**Comment by stevensotelo** [comment]
@ColinKhoury 

9) Fixed
