### ISSUE TITLE
Consider making map instead of list of countries to show on diets and production page

### ISSUE THREAD

**Issue by ColinKhoury** [CIAT-DAPA/cwr_interdependence#8]

**Comment by stevensotelo** [comment]
@ColinKhoury 

Fixed

**Comment by ColinKhoury** [comment]
1. can we please associate Sudan (former) with BOTH Sudan and South Sudan (for the map)

**Comment by stevensotelo** [comment]
@ColinKhoury and @haachicanoy 

To do this is necessary add the ISO of the south sudan in the region content (names_description)

**Comment by ColinKhoury** [comment]
ISO == SSD please add

**Comment by stevensotelo** [comment]
@ColinKhoury 

Fixed

**Comment by ColinKhoury** [comment]
Nice dudes!
